name: CI

on: [push]

jobs:
  linters:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest chardet textract pylint mypy
        if [ -f requirements.txt]; then pip install -r requirements.txt; fi
    - name: flake8
      run: flake8 src --max-line-length=120 --show-source --statistics
    - name: pylint
      run: pylint ./src --rcfile=.pylintrc
    - name: mypy
      run: mypy ./src --strict

  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest textract
        if [ -f requirements.txt]; then pip install -r requirements.txt; fi

    - name: Doctest
      run: python -m doctest -v src/interleave.py

    - name: Unit Tests
      run: |
        cd test
        pytest test_unit.py test_edge_cases.py

    - name: End-to-end Tests
      run: |
        cd test
        pytest test_journey.py

  release-nix:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest textract nuitka
        if [ -f requirements.txt]; then pip install -r requirements.txt; fi
    - name: nuitka
      run: |
        python -m nuitka --standalone src/interleave.py
        ls -l
    - name: zip
      run: |
        zip -l Interleave_Windows.zip README.md src/interleave.py
        zip -ll Interleave_Unix.zip README.md src/interleave.py

  release-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkour@v2
      - name Setup Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest textract nuitka
          pip install -r requirements.txt